### ISSUE TITLE
Maintenance or fork

### ISSUE THREAD

**Issue by martsokha** [Smerity/texting_robots#3]
Would you happen to have any plans to maintain this crate?

I've been using this crate extensively lately and found several bugs that forced me to clone the repo.

- the crate does not find the most specific user as per [Order of precedence for user agents](https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt#order-of-precedence-for-user-agents) but compares them directly. [Code](https://github.com/Smerity/texting_robots/blob/f7a451a399789191f0623dd33b4f753f8e64acfd/src/lib.rs#L397).
- the path `/shark/fish` matches the pattern `/fish*$` because regex does not match the starting position. [Code](https://github.com/Smerity/texting_robots/blob/f7a451a399789191f0623dd33b4f753f8e64acfd/src/minregex.rs#L73).

**Comment by Smerity** [comment]
Hey @martsokha,

I'm glad you've been using this crate extensively!
I do intend to maintain this crate and am interested in the issues you've found.

The `/shark/fish` issue is well spotted and does indeed need to be fixed. I'm surprised the testing, both my own and test cases inspired by Google / Reppy / ..., missed it. Definitely something that should be fixed as it is likely to impact real world use cases.

The order of precedence for user agents is interesting but beyond Google I have rarely seen other crawlers use or reference that. Have you found external documentation? The obvious issue is that if the user agent `robotxt` is allowed to match `user-agent: robot` then it would also match `user-agent: r`? I guess the Google "interpretation" document is indicating all user agent names end with an implicit `*` and it's the longest match that wins. Just seems odd that a crawler `bingo` would be able to leverage permissions for `bing` for example. Perhaps that part of the Google document is really speaking to how their `googlebot` crawlers interact with `robots.txt`.

I don't know how similar or different your new codebase may be but I'd welcome collaboration on code, test cases, or anything else :)

**Comment by martsokha** [comment]
@Smerity Yes, I believe `user-agent: r` should also match, as it is more specific than `*` or no `user-agent` at all, even though having `user-agent: r` does not seem to make any sense. On the other hand, matching `bingo-images` to `bingo` does not seem to be that odd.

**Comment by martsokha** [comment]
There are also several things that I am not sure if correct e.g.
non-prefixed pattern `*abc` and `/*ab` having the same length, which may lead to wrong results for the path `/abcd` in the case of:
```
Disallow: *abc
Allow: /*ab
```
as allowed pattern takes priority. In the fork, I simply add the prefix [[1](https://github.com/xwde/robotxt/blob/732f454a852f30eda9819b51ad2eca811209e1a8/parse/rules.rs#L27)][[2](https://github.com/xwde/robotxt/blob/732f454a852f30eda9819b51ad2eca811209e1a8/parse/rule.rs#L78)].

**Comment by Smerity** [comment]
For now I'm leaving the functionality the same regarding `bing` and `bingo` bot but I'm willing to revisit in the future.

I will keep the allow / disallow length rule in consideration.
