### ISSUE TITLE
Getting regex in allowed function

### ISSUE THREAD

**Issue by dot-pulsar** [Smerity/texting_robots#5]
Hello, I need to determine by which regular expression the checked address will not be indexed. So I decided to offer a solution.

Path: texting_robots/src/lib.rs
```rust
pub fn allowed(&self, url: &str) -> (Option<String>, bool) {
    let url = Self::prepare_url(url);
    if url == "/robots.txt" {
        return (None, true);
    }

    let mut matches: Vec<&_> = self 
        .rules
        .iter()
        .filter(|(rule, _)| rule.is_match(&url))
        .collect();

    matches.sort_by_key(|x| (&x.0, !x.1));

    match matches.first() {
        Some((rx, is_allowed)) => {
            (Some(rx.as_str().to_string()), *is_allowed)
        }
        None => (None, true),
    }
}
```

**Comment by Smerity** [comment]
Hi @dot-pulsar, apology for the delay in reply.

What was the use case for determining whether a specific rule allowed or denied the given URL? I'm curious if there's a broader use case that might need  this type of information exposed.
