### ISSUE TITLE
Expose whether our bot is explicitely referenced

### ISSUE THREAD

**Issue by T-Sujeeban** [Smerity/texting_robots#8]
When checking if an Url is allowed or not, I would like to know if my User-agent was explicitely referenced in the robots.txt file or if the block applied to my User-agent was for all not referenced user-agents ('*')

In the function `Robot::new` we have a variable `references_our_bot` which holds that information. We could simply expose that info through some function. #7

**Comment by Smerity** [comment]
Thanks for continuing the dialogue. I still want to better understand the use case as pull request #7 doesn't actually implement the functionality, it only adds a boolean `references_our_bot`, never setting it to anything.

For example, we could have `references_our_bot` to true if we see any reference to the User Agent but you also note "if the block applied to my User-agent was for all not referenced user-agents", which would instead be a result upon the rule itself.

```
User-agent: *
Disallow: /my-secret-lair/
User-agent: Bob
Disallow: /my-volcano
Disallow: /my-secret-lair/
User-agent: Charlie
Allow: /my-secret-lair/
```

In the case above `references_our_bot` would be true for Bob and Charlie but do we also want to know when a specific rule (such as Bob failing to retrieve `/my-volcano`) is blocking our bot and what if it's in both `*` and our User-agent rule set?

I was hoping you might mention the end use case as that might help clarify some of the thinking around what the best course of action would be.

**Comment by Smerity** [comment]
Closing this as the pull request doesn't yet fill out the required spec and there hasn't been activity. I'm happy to include it if it can be added in a way that works and has unit tests ensuring it's good! :)
